### ISSUE TITLE
Implement Drop for various types

### ISSUE THREAD

**Issue by Blei** [arturoc/gstreamer1.0-rs#12]
It looks like various wrapped C types are never cleaned up.

**Comment by arturoc** [comment]
can you show any specific example?

**Comment by Blei** [comment]
E.g. everything returned by `gst_element_factory_make()` is a `GstObject` which should be unref'd using [`gst_object_unref()`](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer/html/GstObject.html#gst-object-unref) when no longer needed.

**Comment by arturoc** [comment]
i'm checking this and everything allocated with gst_element_factory_make (which is only used in Element::new) is being correctly unref'd by Element's Drop implementation in https://github.com/arturoc/gstreamer1.0-rs/blob/master/src/element.rs#L17-L23, no?

**Comment by arturoc** [comment]
Every object now uses Object or MiniObject now which have their own destructors so everything should be properly freed now

**Comment by Blei** [comment]
You're right, I completely missed that. Thank you!
