### ISSUE TITLE
Error linking gstreamer libraries in Ubuntu

### ISSUE THREAD

**Issue by aldonogueira** [arturoc/gstreamer1.0-rs#26]
Cargo can't find the gstreamer libraries in Ubuntu 16.04 and Ubuntu 17.04 beta.  
It aborts the compilation with
>   = note: /usr/bin/ld: cannot find -lgstvideo-1.0
>           /usr/bin/ld: cannot find -lgstapp-1.0
>           collect2: error: ld returned 1 exit status

I can fix the problem with
> cd /usr/lib/x86_64-linux-gnu
> sudo ln -s libgstapp-1.0.so.0 libgstapp-1.0.so
> sudo ln -s libgstvideo-1.0.so.0 libgstvideo-1.0.so

But it doesn't seem right.

**Comment by arturoc** [comment]
you probably need to install the -dev packages for these, as in libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev...

**Comment by aldonogueira** [comment]
Exactly! The package libgstreamer-plugins-base1.0-dev wasn't installed. Thanks!

**Comment by mario-chirinos** [comment]
I have the same problem but I do have the package libgstreamer-plugins-base1.0-dev installed 


/usr/lib/x86_64-linux-gnu$ ls libgstv* -lhas
   0 lrwxrwxrwx 1 root root   27 Apr 28 17:17 libgstvideo-1.0.so -> libgstvideo-1.0.so.0.1004.0
   0 lrwxrwxrwx 1 root root   27 Apr 28 17:17 libgstvideo-1.0.so.0 -> libgstvideo-1.0.so.0.1004.0
556K -rw-r--r-- 1 root root 553K Apr 28 17:17 libgstvideo-1.0.so.0.1004.0

apt-file find gstreamer-video
gstreamer1.0-plugins-base-doc: /usr/share/gtk-doc/html/gst-plugins-base-libs-1.0/gstreamer-video.html
libgstreamer-plugins-base1.0-dev: /usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-video-1.0.pc
tracker-extract: /usr/share/tracker/extract-rules/90-gstreamer-video-generic.rule
valac-0.34-vapi: /usr/share/vala-0.34/vapi/gstreamer-video-0.10.deps
valac-0.34-vapi: /usr/share/vala-0.34/vapi/gstreamer-video-0.10.vapi
valac-0.34-vapi: /usr/share/vala-0.34/vapi/gstreamer-video-1.0.deps
valac-0.34-vapi: /usr/share/vala-0.34/vapi/gstreamer-video-1.0.vapi
