### ISSUE TITLE
Setting caps on link

### ISSUE THREAD

**Issue by superlou** [arturoc/gstreamer1.0-rs#30]
Is there a way to set the caps when linking two elements?  There is an example for `query_caps`, but I'm not having any luck figuring out how to set the caps on a linked pad.

**Comment by arturoc** [comment]
Hi, sorry for the late reply. There isn't a way to set the caps without directly using the ffi at the moment.

you can get the GstPad using gst_pad_mut() on the gst::Pad and use unsafe ffi functions to set it. if you can put a small example of what you are trying to do i might be able to add this functionality

**Comment by superlou** [comment]
Ideally, I'm looking to implement the `link_filtered` method available in the Python GObject introspection bindings to port [an existing Python project I was developing](https://github.com/superlou/snowman/blob/master/feeds/feed.py#L52) to Rust.

I don't have the Rust version online yet (or working), but I can push what I have tonight.

**Comment by arturoc** [comment]
Just added link_filtered in Element which should be the same functionality you are using in python but let me know if it doesn't work as expected

**Comment by superlou** [comment]
It compiled no problem and seems to run without errors.  I'm having some issues getting output, but I think that's app specific on my end.  Thanks for the patch!
