### ISSUE TITLE
ElementT.play(), pause(), etc should return the correct value

### ISSUE THREAD

**Issue by sdroege** [arturoc/gstreamer1.0-rs#8]
Currently they return bool or nothing. However it is very important that you handle the return values correctly. Especially ASYNC/NO_PREROLL should not be just considered SUCCESS but might require special handling inside the application.

And all state changes can fail, not returning anything is a problem.

**Comment by arturoc** [comment]
i've added GstStateChangeReturn to anything that changes the element state but let me know if you think it should be somewhere else.

thanks!

**Comment by sdroege** [comment]
Thanks, looks complete to me. But I'm currently not using your bindings in an application, I was just looking at the status of the bindings and how the GStreamer API could look like in Rust.

**Comment by sdroege** [comment]
Btw, are there any public projects you're aware of that are using the bindings?

**Comment by arturoc** [comment]
i don't know of any, i've received some pull requests so i suppose some people is using it but don't know of any project that it's using it
